---
name: generate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      base-directory: ${{ github.workspace }}/base/paper
      run-directory: ${{ github.workspace }}/base/paper/run
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 1
      - name: Bootstrap
        run: |
          sudo wget -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          rm -rf ${{ env.base-directory }} && mkdir -p ${{ env.run-directory }}
      - uses: addnab/docker-run-action@v2
        continue-on-error: true
        timeout-minutes: 3
        with:
          image: itzg/minecraft-server:latest
          shell: bash
          options: |
            -v ${{ env.run-directory }}:/data
            -v ${{ github.workspace }}/plugins/paper:/plugins
            -e UID=1001 -e GID=116 -e EULA=TRUE
            -e MAX_TICK_TIME=1 -e MAX_WORLD_SIZE=1
            -e VERSION=1.16.5 -e TYPE=PAPER
          run: |
            /start &
            sleep 60
            killall java
      - name: Cleanup
        run: |
          find . -type f -exec sed -i -e '/^[ \t]*#/d; /^[[:space:]]*$/d; s/[[:blank:]]*$//' {} +
          find . -type f -name "*.jar" -o -empty -delete
        working-directory: ${{ env.base-directory }}
      - name: Merge
        run: |
          set -x
          for f in $(find * -type f -name "*.yml" -o -name "*.yaml" -o -name "*.txt"); do
            echo $f && mkdir -p $(dirname "${{ env.base-directory }}/${f}")
            yq e -MPI2 "${f}" > "${{ env.base-directory }}/${f}"
          done && cp -rn * ${{ env.base-directory }} && rm -rf *
        working-directory: ${{ env.run-directory }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: minecraft-configs
          title: "chore(base): update paper defaults [ci-skip]"
          signoff: true
          committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          commit-message: "chore(deps): update default minecraft configs"
          labels: minecraft/configs
          body: |
            Signed-off-by: Chip Wolf <chipwolf@users.noreply.github.com>
