---
name: generate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      base-directory: ${{ github.workspace }}/base/paper/
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 1
      - name: Bootstrap
        run: |
          sudo wget -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          rm -rf * && mkdir run
        working-directory: ${{ env.base-directory }}
      - uses: addnab/docker-run-action@v2
        continue-on-error: true
        timeout-minutes: 3
        with:
          image: itzg/minecraft-server:latest
          shell: bash
          options: |
            -v ${{ env.base-directory }}/run:/data
            -v ${{ github.workspace }}/plugins/paper:/plugins
            -e UID=1001 -e GID=116 -e EULA=TRUE
            -e MAX_TICK_TIME=1 -e MAX_WORLD_SIZE=1
            -e VERSION=1.16.5 -e TYPE=PAPER
          run: |
            /start &
            sleep 60
            killall java
      - name: Cleanup
        run: |
          find . -type f -exec sed -i -e '/^[ \t]*#/d; /^[[:space:]]*$/d; s/[[:blank:]]*$//' {} +
          find . -type f -name "*.jar" -o -empty -delete
        working-directory: ${{ env.base-directory }}
      - name: Merge
        run: |
          for f in $(find run/* -type f -name ".yml" -o -name ".yaml" -o -name ".txt"); do
            mkdir -p $(dirname "${{ env.base-directory }}../${f}") && touch "${{ env.base-directory }}../${f}"
            yq eval-all -iMPI2 'select(fileIndex == 0) * select(fileIndex == 1)' "${{ env.base-directory }}../${f}" "${f}"
          done
        working-directory: ${{ env.base-directory }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: minecraft-configs
          title: "chore(base): update paper defaults [ci-skip]"
          signoff: true
          committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          commit-message: "chore(deps): update default minecraft configs"
          labels: minecraft/configs
          body: |
            Signed-off-by: Chip Wolf <chipwolf@users.noreply.github.com>
