---
name: minecraft-configs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  get-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 1
      - name: Bootstrap
        run: |
          mkdir -p ${{ github.workspace }}/base/paper/plugins
          rsync -aiP ${{ github.workspace }}/plugins/paper/ ${{ github.workspace }}/base/paper/plugins/
      - uses: addnab/docker-run-action@v2
        continue-on-error: true
        timeout-minutes: 3
        with:
          image: itzg/minecraft-server:latest
          shell: bash
          options: |
            -v ${{ github.workspace }}/base/paper:/data
            -e UID=1001 -e GID=116 
            -e MAX_TICK_TIME=1 -e MAX_WORLD_SIZE=1 -e EULA=TRUE
            -e ALLOW_NETHER=false -e VERSION=1.16.5 -e TYPE=PAPER
          run: |
            /start &
            sleep 60
            killall java
      - name: Cleanup
        run: |
          sudo find ${{ github.workspace }}/base/paper/ -type f -name "*.jar" -delete
          find ${{ github.workspace }}/base/paper/ -type f -exec sed -i -e '/^[ \t]*#/d; /^[[:space:]]*$/d' {} +
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: minecraft-configs
          title: "[minecraft] update default configs [ci-skip]"
          signoff: true
          committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          commit-message: "chore(deps): update default minecraft configs"
          labels: minecraft/configs
