---
name: patch

on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"

jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      base-directory: ${{ github.workspace }}/base/paper/
      overlay-directory: ${{ github.workspace }}/config/paper/
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 1
      - name: Bootstrap
        run: |
          sudo wget -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
      - name: Patch
        run: |
          for f in $(find * -type f); do
            mkdir -p $(dirname ${{ env.base-directory }}/${f}) && touch ${{ env.base-directory }}/${f}
            yq eval-all -MPI2 'select(fileIndex == 0) * select(fileIndex == 1)' ${{ env.base-directory }}/${f} ${f}
          done
        working-directory: ${{ env.overlay-directory }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: minecraft-configs
          title: "chore(final): merge paper patches with base [ci-skip]"
          signoff: true
          committer: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          labels: minecraft/configs
          body: |
            Signed-off-by: Chip Wolf <chipwolf@users.noreply.github.com>
